# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 3

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  version: 3.11
  install:
    - requirements: source/requirements.txt
    - requirements: source/requirements_docs.txt  # Add this line if you have a separate requirements file for documentation
    
  # Install additional packages needed for building the documentation, such as themes
  extra_requirements:
    docs:  # "docs" is the Python environment for building documentation
      - sphinx_book_theme
